### ISSUE TITLE
pkg-config file is broken when CMAKE_INSTALL_{INCLUDE,LIB}DIR is absolute

### ISSUE THREAD

**Issue by alexshpilkin** [powercap/powercap#8]
As per title: `CMakeLists.txt` has
```
set(PKG_CONFIG_EXEC_PREFIX "\${prefix}")
set(PKG_CONFIG_LIBDIR "\${prefix}/${CMAKE_INSTALL_LIBDIR}")
set(PKG_CONFIG_INCLUDEDIR "\${prefix}/${CMAKE_INSTALL_INCLUDEDIR}/${PROJECT_NAME}")
```
and so can’t handle absolute paths in `CMAKE_INSTALL_{INCLUDE,LIB}DIR`. This leads to broken .pc files on NixOS in particular. (Deriving `libdir` from `prefix` rather than `exec_prefix` also seems a bit suspect, but is not the problem here.)

See “[Concatenating paths when building pkg-config files](https://github.com/jtojnar/cmake-snips#concatenating-paths-when-building-pkg-config-files)” for a thorough discussion of the problem and a suggested fix, or [KDE’s extra-cmake-modules](https://invent.kde.org/frameworks/extra-cmake-modules/-/blob/master/modules/ECMGeneratePkgConfigFile.cmake#L166) for a simpler approach.

**Comment by connorimes** [comment]
Thanks for the report.  After just a cursory glance, the simpler approach in KDE's extra-cmake-module checking `IS_ABSOLUTE` seems to be the best approach for now.  I feel it's much too early to move the minimum cmake version to 3.20, and I'd rather not add a dependency on a third-party cmake module, esp. as a temporary solution.

I'm not entirely clear on the `prefix` vs `exec_prefix` distinction.  I see now that the pkg-config man pages use the latter for `libdir`, but most other examples I see use the former (as we do).  There isn't really any textual discussion on the differences though.  I'd be curious if you have a link to one or more authoritative sources that explain.

I'm not able to work on this at the moment, but I'd welcome a PR.

**Comment by alexshpilkin** [comment]
@connorimes The distinction between `prefix` and `exec_prefix` comes from a very different time and I believe is truly unimportant now (as well as seemingly unsupported by CMake), but is described in the [GNU Coding Standards](https://www.gnu.org/prep/standards/html_node/Directory-Variables.html) entry on installation directories if you’re interested. Basically they were intended to allow one to install architecture-independent and -dependent files respectively into different trees, so `bindir`, `libdir`, and so on are resolved relative to `exec_prefix` (which defaults to `prefix`) but `includedir` and `datarootdir` (thus `datadir`, `docdir`, `mandir`, and `infodir`) relative to `prefix` proper.

I hear your preference on the solution, if you’re willing to trust my nearly-nonexistent CMake knowledge I’ll try to come back to this after I finish trawling through other Nix-packaged things which exhibit this problem.
